[project]
name = "dayssincecalc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.5",
    "pydantic>=2.10.0",
    "ruff>=0.7.3",
    "uvicorn>=0.32.1",
]
